# Generated by Django 3.2.8 on 2021-12-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='transaction_id_electrum',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
