# Generated by Django 3.2.8 on 2021-12-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estado_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='transaction_id_electrum',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='transaction_id_todopago',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='wallet_address',
            field=models.CharField(max_length=255),
        ),
    ]
